FROM python:3.8-slim-buster

WORKDIR /app/backend
COPY . .



RUN pip install --upgrade pip && \
    pip install --ignore-installed -r requirements.txt


EXPOSE 8002
ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002" , "--reload"]
