preprocessing:
  drop_columns: ../data/processed/drop_columns.txt
  new_columns: ../data/processed/new_columns.txt
  lable_encod_dir: ../data/processed/lable_encod
  train_path: ../data/raw/train(mini).ftr
  unique_values_path: ../data/processed/unique_values.json
  train_path_proc: ../data/processed/train.csv
  test_path_proc: ../data/processed/test.csv
  log_file: ../data/logging/py_log.log
  test_size: 0.20
  target_column: target
  random_state: 25
  categorical_input_data: ["D_63", "D_64", "D_66", "D_68", "B_30", "B_38", "D_114", "D_116", "D_117", "D_120", "D_126"]

train:
  n_trials: 3 #3
  n_folds: 5 #5
  random_state: 25
  target_column: target
  model_path: ../models/model_catboost.joblib
  study_path: ../models/study.joblib
  metrics_path: ../report/metrics.json
  params_path: ../report/best_params.json

evaluate:
  predict_path: ../data/logging/test.csv

endpoints:
#  train: 'http://fastapi:8002/train'
#  prediction_input: 'http://fastapi:8002/predict_input'
#  prediction_from_file: 'http://fastapi:8002/predict'
  train: 'http://localhost:8002/train'
  prediction_input: 'http://localhost:8002/predict_input'
  prediction_from_file: 'http://localhost:8002/predict'
